// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqlonynufoosraiimswi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxbG9ueW51Zm9vc3JhaWltc3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NzAxOTYsImV4cCI6MjA2NjA0NjE5Nn0.6mo_44N4fvFO7tIhTDt0-_elBf50zCcv8GQOmpg2RoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);